name: Slash-cmd repository deployments
run-name: Slash command repository deployment by @${{ github.event.client_payload.slash_command.args.named.actor }}

on:
  repository_dispatch:
    types: [deploy-command]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub context
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
