name: Slash command dispatch

on:
  issue_comment:
    types: [created]

permissions: write-all

jobs:
  dispatch-slash-command:
    name: Dispatch slash command
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Logs
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          SECRETS_CONTEX: ${{ toJSON(secrets) }}
          VARS_CONTEX: ${{ toJSON(vars) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "$SECRETS_CONTEX"
          echo "$VARS_CONTEX"

      - uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c # v1.2.0
        id: get-token
        with:
          app-id: ${{ vars.SLASH_CMD_DISPATCH_APP_ID }}
          private-key: ${{ secrets.SLASH_CMD_DISPATCH_PRIVATE_KEY }}

      - name: Create repository dispatch event
        id: repository-dispatch
        uses: peter-evans/slash-command-dispatch@a28ee6cd74d5200f99e247ebc7b365c03ae0ef3c # v3.0.1
        with:
          commands: |
            deploy
          issue-type: pull-request
          static-args: |
            actor=${{ github.event.comment.user.login }}
            comment_id=${{ github.event.comment.id }}
          token: ${{ steps.get-token.outputs.token }}

      - name: Fetch pull request details
        id: pull-request
        env:
          PULL_REQUEST_URL: ${{ github.event.issue.pull_request.url }}
        run: |
          RESPONSE="$(curl --fail-with-body $PULL_REQUEST_URL 2>/dev/null)"
          echo "response=${RESPONSE//[$'\t\r\n']}" >> $GITHUB_OUTPUT

      - name: Logs PR
        env:
          PR: ${{ toJSON(fromJSON(steps.pull-request.outputs.response)) }}
        run: echo "$PR"

      - name: Create workflow dispatch event
        id: workflow-dispatch
        uses: peter-evans/slash-command-dispatch@a28ee6cd74d5200f99e247ebc7b365c03ae0ef3c # v3.0.1
        with:
          token: ${{ steps.get-token.outputs.token }}
          commands: |
            deploy-next
          permission: write
          issue-type: pull-request
          dispatch-type: workflow
          static-args: |
            ref=${{ fromJSON(steps.pull-request.outputs.response).head.ref }}
            payload="{\"actor\":\"${{ github.event.comment.user.login }}\",\"comment_id\":\"${{ github.event.comment.id }}\",\"pull_request_title\":\"${{ github.event.issue.title }}\",\"pull_request_url\":\"${{ github.event.issue.pull_request.html_url }}\"}"

      - name: Edit PR comment with error message
        if: steps.workflow-dispatch.outputs.error-message
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.workflow-dispatch.outputs.error-message }}
